# 垃圾桶
Trash:
  name: "&a垃圾桶"
# 全服垃圾桶首页
GlobalTrash:
  name: "&a全服垃圾桶"
# 全服垃圾桶下一页按钮
  Page1Next:
    name: "&a下一页"
    Lore:
      - ""
# 全服垃圾桶分页
GlobalTrash2:
  name: "&a全服垃圾桶"
# 全服垃圾桶分页Gui的下一页按钮
  Pager2Next:
    name: "&a下一页"
    Lore:
      - ""
# 全服垃圾桶分页Gui的上一页按钮
  Back:
    name: "&a上一页"
    Lore:
      - ""

# 转移到垃圾桶提示
TrashTip: "&a物品已转移到全服垃圾桶！"

# 定期清除提示
ClearTip:
  10: "&a垃圾桶清理倒计时 10 秒"
  5: "&a垃圾桶清理倒计时 5 秒"
  3: "&a垃圾桶清理倒计时 3 秒"
  2: "&a垃圾桶清理倒计时 2 秒"
  1: "&a垃圾桶清理倒计时 1 秒"
  0: "&a垃圾桶清理完毕"

# 清除间隔（分钟）
ClearInterval: 5
# 再开始倒计时提示的时候是否让玩家不能再通过指令打开垃圾桶，但可以打开全服垃圾桶，true未开启，false为关闭
ClearTrashDisabled: true
# 玩家因为上面的原因无法打开垃圾桶时的提示
ClearTrashDisabledTip: "&a倒计时结束前无法打开垃圾桶"