# 垃圾桶
Trash:
  name: "&6垃圾桶"
# 全服垃圾桶首页
GlobalTrash:
  name: "&a全服垃圾桶"
# 全服垃圾桶下一页按钮
  Page1Next:
    name: "&f下一页"
    Lore:
      - "&8进入下一页"
# 全服垃圾桶分页
GlobalTrash2:
  name: "&a全服垃圾桶"
# 全服垃圾桶分页Gui的下一页按钮
  Pager2Next:
    name: "&f下一页"
    Lore:
      - "&8进入下一页"
# 全服垃圾桶分页Gui的上一页按钮
  Back:
    name: "&f上一页"
    Lore:
      - "&8返回上一页"

# 转移到垃圾桶提示
TrashTip: "&a[&e寄寄の家&a] &7物品已存入 &6全服垃圾桶"

# 定期清除提示
ClearTip:
  10: "&a[&c寄寄の家&a] &7距离垃圾桶清理还有 &610 &7秒"
  5: "&a[&c寄寄の家&a] &7距离垃圾桶清理还有 &65 &7秒"
  3: "&a[&c寄寄の家&a] &7距离垃圾桶清理还有 &63 &7秒"
  2: "&a[&c寄寄の家&a] &7距离垃圾桶清理还有 &62 &7秒"
  1: "&a[&c寄寄の家&a] &7距离垃圾桶清理还有 &61 &7秒"
  0: "&a[&e寄寄の家&a] &7垃圾桶清理完毕!"

# 清除间隔（分钟）
ClearInterval: 5
# 再开始倒计时提示的时候是否让玩家不能再通过指令打开垃圾桶，但可以打开全服垃圾桶，true未开启，false为关闭
ClearTrashDisabled: true
# 玩家因为上面的原因无法打开垃圾桶时的提示
ClearTrashDisabledTip: "&a[&c寄寄の家&a] &7垃圾桶即将清理，因此你无法打开!"