name: XLRTrash
version: 1.0
main: main.xlingran.Shan
api-version: 1.21.1
author: Shan
description: 全服垃圾桶

commands:
  xlrtrash:
    description: 打开垃圾桶
    usage: /xlrtrash
  xlrglobaltrash:
    description: 打开全服垃圾桶
    usage: /xlrglobaltrash
